services:
  - name: xbsapi
    type: web
    env: docker
    repo: https://github.com/mrusme/xbsapi.git
    branch: master
    numInstances: 1
    healthCheckPath: /api/v1/info
    envVars:
      - key: XBSAPI_SERVER_BINDIP
        value: "0.0.0.0"
      - key: DATABASE_URL
        fromDatabase:
          name: xbsapidb
          property: connectionString
    autoDeploy: false

databases:
  - name: xbsapidb
    databaseName: xbsapi
    user: xbsapi
    ipAllowList: []
    postgresMajorVersion: 14

