definitions:
  bookmarks.BookmarkCreateModel:
    properties:
      version:
        type: string
    required:
    - version
    type: object
  bookmarks.BookmarkCreateResponse:
    properties:
      bookmark:
        $ref: '#/definitions/bookmarks.BookmarkShowModel'
      message:
        type: string
      success:
        type: boolean
    type: object
  bookmarks.BookmarkShowModel:
    properties:
      bookmarks:
        type: string
      id:
        type: string
      lastUpdated:
        type: string
      version:
        type: string
    type: object
  bookmarks.BookmarkShowResponse:
    properties:
      bookmark:
        $ref: '#/definitions/bookmarks.BookmarkShowModel'
      message:
        type: string
      success:
        type: boolean
    type: object
  bookmarks.BookmarkUpdateModel:
    properties:
      bookmarks:
        type: string
      lastUpdated:
        type: string
    required:
    - bookmarks
    - lastUpdated
    type: object
  bookmarks.BookmarkUpdateResponse:
    properties:
      bookmark:
        $ref: '#/definitions/bookmarks.BookmarkShowModel'
      message:
        type: string
      success:
        type: boolean
    type: object
  infos.InfoShowModel:
    properties:
      location:
        type: string
      maxSyncSize:
        type: integer
      message:
        type: string
      status:
        type: integer
      version:
        type: string
    type: object
info:
  contact: {}
paths:
  /bookmarks:
    post:
      consumes:
      - application/json
      description: Add a new bookmark sync
      parameters:
      - description: Bookmark sync
        in: body
        name: bookmark
        required: true
        schema:
          $ref: '#/definitions/bookmarks.BookmarkCreateModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/bookmarks.BookmarkCreateResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/bookmarks.BookmarkCreateResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/bookmarks.BookmarkCreateResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/bookmarks.BookmarkCreateResponse'
      security:
      - BasicAuth: []
      summary: Create a bookmark sync
      tags:
      - bookmarks
  /bookmarks/{id}:
    get:
      consumes:
      - application/json
      description: Get bookmark sync version by ID
      parameters:
      - description: Bookmark ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/bookmarks.BookmarkShowResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/bookmarks.BookmarkShowResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/bookmarks.BookmarkShowResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/bookmarks.BookmarkShowResponse'
      security:
      - BasicAuth: []
      summary: Show a bookmark sync version
      tags:
      - bookmarks
    put:
      consumes:
      - application/json
      description: Update an existing bookmark sync
      parameters:
      - description: Bookmark ID
        in: path
        name: id
        required: true
        type: string
      - description: Update
        in: body
        name: bookmark
        required: true
        schema:
          $ref: '#/definitions/bookmarks.BookmarkUpdateModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/bookmarks.BookmarkUpdateResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/bookmarks.BookmarkUpdateResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/bookmarks.BookmarkUpdateResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/bookmarks.BookmarkUpdateResponse'
      security:
      - BasicAuth: []
      summary: Update a bookmark sync
      tags:
      - bookmarks
  /infos:
    get:
      consumes:
      - application/json
      description: Get all infos
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/infos.InfoShowModel'
      security:
      - BasicAuth: []
      summary: List infos
      tags:
      - infos
swagger: "2.0"
