name: Docker

on:
  push:
    branches:
      - "master"
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: login docker
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" \
            | docker login \
              -u "${{ secrets.DOCKER_USERNAME }}" \
              --password-stdin
      - name: setup qemu
        uses: docker/setup-qemu-action@v2
      - name: setup buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: build image
        run: |
          docker buildx build \
            --push \
            --tag "mrusme/xbsapi:latest" \
            --tag "mrusme/xbsapi:${{ github.ref_name }}" \
            --platform \
              "linux/i386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64" \
            .

