name: Tests

on: [push]

jobs:
  tests:
    defaults:
      run:
        shell: bash

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Install dependencies
        run: make install-deps

      - name: Build
        run: make

      - name: Go test
        run: go test -v ./

      - name: Run xbsapi in background
        run: |
          ./xbsapi &

      - name: Run integration tests
        env:
          XBSAPI_API_URL: http://127.0.0.1:8000/api
        run: |
          ./test.sh true

